DELETE FROM texts;
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Einkaufen', 'Liebe Tanja, kannst du bitte einkaufen? Ich habe heute Nachmittag keine Zeit und ich möchte heute Abend kochen. Ich brauche noch Kartoffeln, Paprika, Tomaten und Zwiebeln. Für das Frühstück brauchen wir Kaffee, Tee, Brot, Butter, Marmelade, Käse und Wurst. Kannst du auch Schokolade und Cola mitbringen? Vielen Dank! Liebe Grüße Mama');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Familienfoto', 'Timo erzählt: Das ist meine Mutter. Sie trägt ein Kleid. Das Kleid ist blau. Das ist mein Vater. Er trägt Jeans und ein Hemd. Das Hemd ist weiß. Ich habe auch eine Schwester. Sie ist zwölf. Und ich habe einen Hund. Er ist groß und weiß und heißt Benni. Wir lieben Benni. Hier sind auch meine Tante Monika und mein Onkel Anton. Sie haben auch zwei Kinder, zwei Mädchen. Das sind meine Cousinen. Sie heißen Tina und Nina. Sie sind fünf Jahre alt. Sie sind Zwillinge. Tina und Nina spielen gern mit Benni. Meine Oma und mein Opa sind schon alt. Sie sitzen hier. Meine Oma kocht super. Ich liebe ihre Nudeln mit Tomatensauce.');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Freunde?', 'Kathrin ist im Bus. Sie hört Musik und schreibt eine SMS. Der Bus hält. Chris steigt ein. Chris sieht Kathrin und sagt: Hallo Kathrin!
Aber Kathrin hört ihn nicht. Sie hört Musik. Die Musik ist laut. Chris geht zu Kathrin und sagt: Hallo! Kathrin! Wie geht’s?
Jetzt sieht Kathrin Chris. Sie lacht und sagt: Hallo Chris! Mir geht’s gut. Und dir?
Chris: Auch gut. Kathrin und Chris fahren Bus. Sie sagen nichts. Chris will fragen: Möchtest du heute ins Kino gehen? Kathrin will sagen: Möchtest du heute mit mir Kaffee trinken? Aber Kathrin sagt nur: Möchtest du Musik hören? Und Chris sagt: „Ja.“ Sie hören Musik. Und dann steigen sie aus, weil sie an der Uni sind. Kathrin geht zur Vorlesung und Chris geht zum Englischkurs. Und wann gehen sie Kaffee trinken?');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Einkauf für die Geburtstagsparty', 'Susi wird nächste Woche 25. Sie möchte ihren Geburtstag groß feiern. Sie hat schon viele Freunde eingeladen. Jetzt muss sie für das Fest einkaufen. Zuerst geht sie auf den Markt. Dort möchte sie Obst und Gemüse kaufen. Sie kauft Äpfel, Bananen, Orangen und Weintrauben für einen Obstsalat und Tomaten, Salat, eine Gurke und Paprika. Auf dem Markt trifft sie ihre Freundin. Sie trinken zusammen einen Kaffee. Dann muss Susi zum Supermarkt und zum Bäcker gehen. Zu Hause muss Susi noch aufräumen ihr Zimmer dekorieren, Suppe kochen, Salat vorbereiten und Getränke und Gläser auf den Tisch stellen. Endlich ist alle fertig. Bald kommen ihre Freunde und Susi freut sich auf die Party.');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Saarbrücken', 'Saarbrücken ist eine kleine Großstadt im Westen von Deutschland. Saarbrücken liegt im Saarland. Das ist das kleinste Bundesland in Deutschland. Westlich von Saarbrücken kommt gleich Frankreich. Mit dem Zug ist man in einer Stunde in Metz, in zwei Stunden in Paris. Aber nach Berlin fährt man 8 Stunden.
In Saarbrücken gibt es viele Bars und Cafés. Die Leute sitzen gern auf dem St. Johanner Markt und trinken Bier oder eine Cola. Im Sommer sind viel junge Leute, aber auch Familien am Staden. Sie sitzen dort und grillen oder sie spielen Fußball oder Volleyball. Viele fahren auch mit dem Fahrrad. Natürlich gibt es auch Theater und Kinos.
Am Samstag gehen viele Leute aus Frankreich und aus Deutschland zum Einkaufen in die Stadt. Man hört manchmal Deutsch, manchmal Französisch.
Kommen Sie und besuchen Sie Saarbrücken!');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Ein Wochenende in den Bergen', 'Am Wochenende war ich mit Nadja Skifahren. Das war ganz toll. Wir haben eine Ferienwohnung gemietet und sind mit dem Auto in die Berge gefahren. Freitagnachmittag sind wir losgefahren. Wir sind abends angekommen und haben zuerst einen Spaziergang durch den Schnee gemacht. Es war richtig kalt und es hat ein bisschen geschneit. Danach haben wir in einer Bar etwas gegessen und ein Bier getrunken. Am Samstag sind wir den ganzen Tag Ski gefahren. Am Abend sind wir schon um 10 Uhr ins Bett gegangen, weil wir so müde waren. Am Sonntag sind wir ganz früh aufgestanden. Wir sind noch bis Mittags Ski gefahren. Dann mussten wir nach Hause fahren. Wir hatten Glück mit dem Wetter. Die Sonne hat geschienen und der Schnee war toll.');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Ein Ausflug mit dem Zug', 'Du möchtest einen Ausflug mit deinen Freunden machen? Und du möchtest mit dem Zug fahren? Dann kauf dir am besten das "Schönes-Wochenende-Ticket". Mit diesem Ticket kannst du mit 4 Freunden überall hinfahren. Du darfst aber nur langsame Züge benutzen. Das Ticket kannst du am Automaten am Bahnhof kaufen. Es kostet 42 Euro. Wenn du viel Zeit und Geduld hast, kannst du in jede deutsche Stadt fahren. Aber das dauert sehr lange.
Natürlich gibt es auch noch viele andere Tickets. Also frage am besten einen Freund, welches Ticket für dich am besten ist.');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Einladung zur Party', 'Lieber Max,
morgen habe ich Geburtstag und deshalb möchte ich am Samstag feiern. Ich lade dich herzlich zu meiner Party ein. Wir möchten um 19 Uhr im Garten feiern. Kannst du einen Salat mitbringen? Vergiss deinen Pullover nicht.
Bitte schreibe mir, ob du kommen kannst.
Herzliche Grüße
Maria');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Einladung zum Essen', 'Liebe Sandra, lieber Jens,
wir sind umgezogen und möchten deshalb feiern. Wir wohnen jetzt in der Altstadt in einer schönen Wohnung mit Balkon. Die möchten wir euch zeigen. Wir laden euch herzlich zu einem Abendessen ein, am Samstag Abend um 19 Uhr. Tina und Roland kommen auch.
Bitte sagt uns schnell, ob ihr kommen könnt.
Wir freuen uns auf euch!
Liebe Grüße
Sonja und Ralf');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Karriere ohne Casting', 'Immer wieder Demotapes aufnehmen, vor Freunden spielen, vielleicht mal als Vorband, und das alles für lau. Wer als Musiker Karriere machen will, braucht Geduld und Glück. Das neue Portal www.nucomer.tv möchte nun beim Aufstieg in die Charts helfen. "Es gibt viele junge Musiker, aber zu wenig Leute, die sich ernsthaft um den Nachwuchs kümmern", sagt Portalgründer Friedhelm Osada. "Wir möchten ihnen eine Plattform bieten, auf der sie sich der breiten Masse präsentieren können, ohne sich in Castingshows prostituieren zu müssen." Der ehemalige Tourneeveranstalter kennt das Business seit 35 Jahren. Seine Idee: Jeder kann sich auf der Website einloggen und kostenlos bis zu drei Titel hochladen. Die Community stimmt mit einem "Like"-Button über die Songs ab. Wer besonders gut abschneidet, dem bieten die Projektgründer ihre Unterstützung an. "Künstler mit Potential können wir unter Vertrag nehmen oder an Labels weitervermitteln", sagt Osada. Mit Tausenden Fans im Rücken klopft es sich nämlich leichter an die Türen von Plattenfirmen an');
INSERT INTO `softpro_ws15_1`.`texts` (`id`, `name`, `fulltext`) VALUES (NULL, 'Tornister für Ärzte', 'In Äthiopien sollte man besser nicht krank werden. Erstens kommen auf 100000 Menschen nur 3 Ärzte (in Deutschland sind es 370), zweitens sind die hygienischen Bedingungen in Krankenhäusern und Praxen genauso schlecht wie in vielen anderen Entwicklungsländern. Die angehenden Ingenieure Philipp Odernheimer, 24, Raphael Schönweitz, 25, und der Wirtschaftswissenschaftler Martin Reh, 30, haben nun eine Art Medizinerrucksack entwickelt, der die Situation in Äthiopien und anderswo verbessern soll. Der 25 Kilo schwere Tornister kann auch im entlegensten Winkel der Erde genutzt werden und mit Hilfe von Sonnenenergie binnen einer Stunde schmutziges oder salziges in sauberes Wasser umwandeln. Das kann dann ruhigen Gewissens zur Wundbehandlung, für kleine Operationen und zur Herstellung von Infusionen verwendet werden. Außerdem erzeugt der Rucksack Hitze und Kälte: So lassen sich Operationsbestecke sterilisieren und Medikamente lagern. Ende des Jahres soll die Produktion des Geräts beginnen - und damit Phase zwei: Die Jungunternehmer wollen Firmen, Organisationen und Privatpersonen dafür gewinnen, Rucksäcke zu kaufen, für ca. 4000 Euro pro Stück via www.rucksackspende.de. Der Käufer darf bestimmen, wer den Tornister nutzen darf und wo er eingesetzt werden soll.');
