ALTER TABLE `results_v0`
	ADD COLUMN `text_id` INT NULL DEFAULT NULL AFTER `username`,
	ADD COLUMN `score1` FLOAT NULL DEFAULT NULL AFTER `text_id`,
	ADD COLUMN `score2` FLOAT NULL DEFAULT NULL AFTER `score1`,
	ADD COLUMN `score3` FLOAT NULL DEFAULT NULL AFTER `score2`;
