ALTER TABLE `results_v0`
	ADD COLUMN `text_id` INT NULL DEFAULT NULL AFTER `username`,
	ADD COLUMN `score` FLOAT NULL DEFAULT NULL AFTER `text_id`,
	ADD COLUMN `correct_words` FLOAT NULL DEFAULT NULL AFTER `score`,
	ADD COLUMN `total_words` FLOAT NULL DEFAULT NULL AFTER `correct_words`;
